import type { Database } from './sqlEngine';

export const DB_COMPANY: Database = {
  employees: [
    { id: 1, name: '田中太郎', age: 28, department_id: 1, salary: 450000, hire_date: '2022-04-01' },
    { id: 2, name: '佐藤花子', age: 32, department_id: 2, salary: 420000, hire_date: '2020-09-15' },
    { id: 3, name: '鈴木一郎', age: 45, department_id: 1, salary: 680000, hire_date: '2015-04-01' },
    { id: 4, name: '山田美咲', age: 25, department_id: 3, salary: 380000, hire_date: '2023-04-01' },
    { id: 5, name: '高橋健太', age: 38, department_id: 1, salary: 550000, hire_date: '2018-07-01' },
    { id: 6, name: '伊藤由美', age: 29, department_id: 2, salary: 410000, hire_date: '2021-10-01' },
    { id: 7, name: '渡辺誠', age: 41, department_id: 3, salary: 520000, hire_date: '2016-01-15' },
    { id: 8, name: '中村あい', age: 23, department_id: 1, salary: 350000, hire_date: '2024-04-01' },
    { id: 9, name: '小林翔', age: 35, department_id: 4, salary: 480000, hire_date: '2019-06-01' },
    { id: 10, name: '加藤結衣', age: 27, department_id: 4, salary: 400000, hire_date: '2022-10-01' },
  ],
  departments: [
    { id: 1, name: '開発部', floor: 5, manager_id: 3 },
    { id: 2, name: 'デザイン部', floor: 4, manager_id: 2 },
    { id: 3, name: 'マーケ部', floor: 3, manager_id: 7 },
    { id: 4, name: '営業部', floor: 2, manager_id: 9 },
    { id: 5, name: '人事部', floor: 6, manager_id: null },
  ],
  projects: [
    { id: 1, name: 'Webリニューアル', budget: 5000000, status: '進行中' },
    { id: 2, name: 'モバイルアプリ', budget: 8000000, status: '進行中' },
    { id: 3, name: 'データ基盤構築', budget: 12000000, status: '計画中' },
    { id: 4, name: '社内ツール改善', budget: 2000000, status: '完了' },
  ],
  assignments: [
    { employee_id: 1, project_id: 1, role: 'リード' },
    { employee_id: 1, project_id: 2, role: 'メンバー' },
    { employee_id: 3, project_id: 2, role: 'リード' },
    { employee_id: 5, project_id: 1, role: 'メンバー' },
    { employee_id: 5, project_id: 3, role: 'リード' },
    { employee_id: 6, project_id: 1, role: 'デザイナー' },
    { employee_id: 8, project_id: 2, role: 'メンバー' },
    { employee_id: 9, project_id: 4, role: 'リード' },
    { employee_id: 10, project_id: 4, role: 'メンバー' },
  ],
};

export const DB_SHOP: Database = {
  products: [
    { id: 1, name: 'ノートPC', category: '電子機器', price: 98000, stock: 15, release_date: '2025-06-01' },
    { id: 2, name: 'マウス', category: '周辺機器', price: 3500, stock: 120, release_date: '2025-03-15' },
    { id: 3, name: 'キーボード', category: '周辺機器', price: 8900, stock: 85, release_date: '2025-04-01' },
    { id: 4, name: 'モニター', category: '電子機器', price: 45000, stock: 30, release_date: '2025-07-20' },
    { id: 5, name: 'USBハブ', category: '周辺機器', price: 2800, stock: 200, release_date: '2024-12-01' },
    { id: 6, name: 'ウェブカメラ', category: '周辺機器', price: 6500, stock: 60, release_date: '2025-01-10' },
    { id: 7, name: 'タブレット', category: '電子機器', price: 72000, stock: 20, release_date: '2025-09-01' },
    { id: 8, name: 'SSD 1TB', category: 'ストレージ', price: 12000, stock: 50, release_date: '2025-02-28' },
    { id: 9, name: 'HDD 4TB', category: 'ストレージ', price: 9800, stock: 35, release_date: '2024-10-15' },
    { id: 10, name: 'USB充電器', category: '周辺機器', price: 4200, stock: 150, release_date: '2025-05-01' },
  ],
  customers: [
    { id: 1, name: 'Alpha社', region: '東京', plan: 'プレミアム', registered: '2024-01-10' },
    { id: 2, name: 'Beta株式会社', region: '大阪', plan: 'スタンダード', registered: '2024-03-22' },
    { id: 3, name: 'Gamma工業', region: '名古屋', plan: 'プレミアム', registered: '2023-11-05' },
    { id: 4, name: 'Delta商事', region: '東京', plan: 'フリー', registered: '2024-06-18' },
    { id: 5, name: 'Epsilon技研', region: '福岡', plan: 'スタンダード', registered: '2024-02-14' },
    { id: 6, name: 'Zeta合同', region: '札幌', plan: 'フリー', registered: '2024-08-30' },
  ],
  orders: [
    { id: 1, customer_id: 1, product_id: 1, quantity: 1, order_date: '2026-01-15', status: '完了' },
    { id: 2, customer_id: 2, product_id: 2, quantity: 3, order_date: '2026-01-20', status: '完了' },
    { id: 3, customer_id: 1, product_id: 4, quantity: 2, order_date: '2026-02-01', status: '発送中' },
    { id: 4, customer_id: 3, product_id: 3, quantity: 1, order_date: '2026-02-10', status: '完了' },
    { id: 5, customer_id: 4, product_id: 7, quantity: 1, order_date: '2026-02-15', status: 'キャンセル' },
    { id: 6, customer_id: 2, product_id: 5, quantity: 5, order_date: '2026-02-20', status: '完了' },
    { id: 7, customer_id: 5, product_id: 6, quantity: 2, order_date: '2026-03-01', status: '発送中' },
    { id: 8, customer_id: 3, product_id: 8, quantity: 3, order_date: '2026-03-05', status: '完了' },
    { id: 9, customer_id: 1, product_id: 10, quantity: 10, order_date: '2026-03-10', status: '完了' },
    { id: 10, customer_id: 3, product_id: 1, quantity: 2, order_date: '2026-03-15', status: '発送中' },
    { id: 11, customer_id: 5, product_id: 9, quantity: 1, order_date: '2026-03-18', status: '完了' },
    { id: 12, customer_id: 2, product_id: 4, quantity: 1, order_date: '2026-03-20', status: '完了' },
  ],
  reviews: [
    { id: 1, product_id: 1, customer_id: 1, rating: 5, comment: '素晴らしい性能' },
    { id: 2, product_id: 1, customer_id: 3, rating: 4, comment: 'コスパ良い' },
    { id: 3, product_id: 2, customer_id: 2, rating: 3, comment: '普通' },
    { id: 4, product_id: 4, customer_id: 1, rating: 5, comment: '画質最高' },
    { id: 5, product_id: 7, customer_id: 4, rating: 2, comment: '期待外れ' },
    { id: 6, product_id: 3, customer_id: 3, rating: 4, comment: '打鍵感が良い' },
    { id: 7, product_id: 8, customer_id: 3, rating: 5, comment: '速度が段違い' },
    { id: 8, product_id: 6, customer_id: 5, rating: 3, comment: '画質はまあまあ' },
    { id: 9, product_id: 5, customer_id: 2, rating: 4, comment: '便利' },
  ],
};

export const DB_SCHOOL: Database = {
  students: [
    { id: 1, name: '青木優斗', grade: 1, class: 'A', club: 'プログラミング部' },
    { id: 2, name: '石川さくら', grade: 1, class: 'B', club: 'プログラミング部' },
    { id: 3, name: '上田翼', grade: 2, class: 'A', club: '数学研究会' },
    { id: 4, name: '遠藤真央', grade: 2, class: 'A', club: null },
    { id: 5, name: '大西凛', grade: 2, class: 'B', club: 'プログラミング部' },
    { id: 6, name: '片山蓮', grade: 3, class: 'A', club: '数学研究会' },
    { id: 7, name: '木下ひなた', grade: 3, class: 'B', club: '英語部' },
    { id: 8, name: '黒田大輝', grade: 3, class: 'A', club: null },
    { id: 9, name: '佐々木陽', grade: 1, class: 'A', club: '英語部' },
    { id: 10, name: '島田美月', grade: 1, class: 'B', club: null },
  ],
  subjects: [
    { id: 1, name: '数学', teacher: '山本先生' },
    { id: 2, name: '英語', teacher: '田村先生' },
    { id: 3, name: 'プログラミング', teacher: '高野先生' },
    { id: 4, name: '物理', teacher: '森先生' },
  ],
  scores: [
    { student_id: 1, subject_id: 1, score: 85 },
    { student_id: 1, subject_id: 2, score: 72 },
    { student_id: 1, subject_id: 3, score: 95 },
    { student_id: 2, subject_id: 1, score: 78 },
    { student_id: 2, subject_id: 2, score: 88 },
    { student_id: 2, subject_id: 3, score: 90 },
    { student_id: 3, subject_id: 1, score: 92 },
    { student_id: 3, subject_id: 2, score: 65 },
    { student_id: 3, subject_id: 4, score: 88 },
    { student_id: 4, subject_id: 1, score: 70 },
    { student_id: 4, subject_id: 2, score: 82 },
    { student_id: 5, subject_id: 1, score: 88 },
    { student_id: 5, subject_id: 3, score: 92 },
    { student_id: 5, subject_id: 4, score: 75 },
    { student_id: 6, subject_id: 1, score: 98 },
    { student_id: 6, subject_id: 2, score: 70 },
    { student_id: 6, subject_id: 4, score: 95 },
    { student_id: 7, subject_id: 2, score: 96 },
    { student_id: 7, subject_id: 3, score: 60 },
    { student_id: 8, subject_id: 1, score: 55 },
    { student_id: 8, subject_id: 4, score: 62 },
    { student_id: 9, subject_id: 2, score: 90 },
    { student_id: 9, subject_id: 3, score: 78 },
    { student_id: 10, subject_id: 1, score: 68 },
    { student_id: 10, subject_id: 2, score: 74 },
  ],
};

export const ALL_DBS: Database = {
  ...DB_COMPANY,
  ...DB_SHOP,
  ...DB_SCHOOL,
};

export const CHAPTERS = [
  { id: 'basics', title: '基本操作', emoji: '📗', color: '#43A047', description: 'SELECT / WHERE / ORDER BY をマスター' },
  { id: 'filtering', title: 'データ抽出', emoji: '🔍', color: '#0078D4', description: 'LIKE / IN / BETWEEN / DISTINCT で絞り込み' },
  { id: 'aggregation', title: '集計・グループ化', emoji: '📊', color: '#F9A825', description: 'GROUP BY / HAVING / 集計関数' },
  { id: 'joins', title: 'テーブル結合', emoji: '🔗', color: '#E65100', description: 'JOIN で複数テーブルを結合' },
  { id: 'advanced', title: '実践クエリ', emoji: '🏆', color: '#D32F2F', description: 'CASE / 算術演算 / 複合クエリ' },
] as const;

export type ChapterId = (typeof CHAPTERS)[number]['id'];
